language: python

cache: pip

python:
  - "3.5"
  - "3.6"
  - "3.7"

dist: xenial

before_install:
  - sudo apt-get update
  - sudo apt-get install -y wget git portaudio19-dev libpulse-dev vlc-nox shellcheck sox libatlas-base-dev
  - sudo wget http://mirrors.kernel.org/ubuntu/pool/universe/s/swig/swig3.0_3.0.12-2_amd64.deb
  - sudo dpkg -i swig3.0_3.0.12-2_amd64.deb
  - sudo ln -s /usr/bin/swig3.0 /usr/local/bin/swig
  - pip install pipenv

install:
  - pipenv install --dev --deploy
  - pipenv install git+https://github.com/Kitt-AI/snowboy.git#egg=snowboy || true
#  - yes | pip install git+https://github.com/duxingkei33/orangepi_PC_gpio_pyH3.git#egg=pyA20 -v

script:
  - pipenv run lint
  - pipenv run yamlcheck
  - pipenv run shlint
